export default 
{
  "cursos": [
    {
      "id": 1,
      "idhotmart": 1197438,
      "ad_id": 0,
      "title": "Salsa Caleña Nivel Básico",
      "slug": "salsa-calena-nivel-basico",
      "content": "En este curso aprenderás todo lo necesario para ser un gran bailador de Salsa, dominar el estilo y los diferentes pasos... ",
      "body": "En este curso aprenderás todo lo necesario para ser un gran bailador de Salsa, dominar el estilo y los diferentes pasos que te harán brillar en una pista de baile, aprenderás a interiorizar la salsa y vivir lo emocionante de bailar a toda velocidad. Vive la experiencia de dominar este estilo, al lado de los mejores exponentes de la salsa caleña, Viviana Vargas Campeona mundial de salsa y Brandon Pérez estandarte de la salsa Caleña ambos bailarines del show Delirio.Este curso se compone de 3 Módulos, 7 Horas, 70 Clases, 4 Niveles, 6 Videos por nivel.  (Módulos= Estilo Parejas, Estilo Mujeres, Estilo Hombres)",
      "vsl": "",
      "author": "",
      "evaluacion": "4.6",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2,
      "precio": 40
    },
    {
      "id": 2,
      "idhotmart": 608106,
      "ad_id": 0,
      "title": "Divertidas clases de Baile",
      "slug": "divertidas-clases-de-baile",
      "content": "Acceso total a más de 30 coreografías de diferentes ritmos y niveles de dificultad. Material exclusivo con explicación lenta y paso a paso... ",
      "body": "Somos especialistas en alumnos principiantes y gente que necesita una buena guía.",
      "vsl": "",
      "author": "",
      "evaluacion": "5.0",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "por año",
      "comission": 20,
      "cashback": 1,
      "precio": 25
    },
    {
      "id": 3,
      "idhotmart": 1304786,
      "ad_id": 0,
      "title": "Salsa Caleña Nivel Intermedio",
      "slug": "salsa-calena-nivel-intermediario",
      "content": "En este curso aprenderás a bailar salsa caleña a un nivel intermedio, es necesario que ya manejan lo básico de la salsa caleña... ",
      "body": "En este curso aprenderás a bailar salsa caleña a un nivel intermedio, es necesario que ya manejan lo básico de la salsa caleña, si apenas vas a empezar te invitamos a que hagas primero nuestro curso de salsa caleña nivel básico. Aprenderas mas paso y vueltas de salsa caleña, empezaremos a combinar todo esto para sacar rutinas así podrás practicar y aplicarlas a tu baile social. Haremos diferentes ejercicios para mejorar tu técnica y empieces a verte como un bailador social con mucho estilo y bailando a toda velocidad. Vive la experiencia de dominar este estilo, al lado de los mejores exponentes de la salsa caleña, Viviana Vargas Campeona mundial de salsa y Brandon Pérez estandarte de la salsa Caleña ambos bailarines del show Delirio.",
      "vsl": "",
      "author": "",
      "evaluacion": "5.0",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2,
      "precio": 40
    },
    {
      "id": 4,
      "idhotmart": 1403936,
      "ad_id": 0,
      "title": "Salsa Caleña Nivel Avanzado",
      "slug": "salsa-calena-nivel-avanzado",
      "content": "En este curso aprenderás a bailar salsa caleña a un nivel AVANZADO, por eso la dificultad de nuestros pasos será más alta para que así logres una mejor habilidad en tu baile... ",
      "body": "En este curso aprenderás a bailar salsa caleña a un nivel AVANZADO, por eso la dificultad de nuestros pasos será más alta para que así logres una mejor habilidad en tu baile, manejas mas paso y vueltas de salsa caleña, empezaremos a combinar todo esto para sacar rutinas, así podrás practicar y aplicarlas a tu baile social, haremos diferentes ejercicios para mejorar tu técnica y empieces a verte como un bailador social de clase mundial, bailando a toda velocidad. Vive la mejor experiencia de baile, al lado de los exponentes de la salsa caleña más destacados, Viviana Vargas Campeona mundial de salsa y Brandon Pérez, estandarte de la salsa Caleña ambos bailarines del show Delirio.",
      "vsl": "",
      "author": "",
      "evaluacion": "5.0",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2,
      "precio": 40.0
    },
    {
      "id": 5,
      "idhotmart": 1428112,
      "ad_id": 0,
      "title": "3x1 - Salsa Caleña Taller Online Full Pack",
      "slug": "salsa-calena-taller-online-full-pack",
      "content": "Este curso es el mas completo entrenamiento para aprender Salsa Caleña, aquí podrás encontrar tres cursos en uno solo: Nivel Básico, Nivel Intermedio y Nivel avanzado... ",
      "body": "Este curso es el mas completo entrenamiento para aprender Salsa Caleña, aquí podrás encontrar tres cursos en uno solo: Nivel Básico, Nivel Intermedio y Nivel avanzado, para que hagas tu proceso completo con nosotros. Dictados por los campeones mundiales de salsa; Brando Pérez y Viviana Vargas, con una metodología comprobada 100%, adquirida de años de clases presenciales y es así donde se crea este entrenamiento de salsa para que ustedes lo puedan hacer en casa. El curso es 100% virtual y es vitalicio nunca se va a vencer pa a que lo veas las veces que quieras.",
      "vsl": "",
      "author": "",
      "evaluacion": "5.0",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 8,
      "precio": 120
    },
    {
      "id": 6,
      "idhotmart": 2090325,
      "ad_id": 0,
      "title": "Baila con Laura: Ritmos Latinos",
      "slug": "baila-con-laura-ritmos-latinos",
      "content": "Es un super video curso FULL HD, que te enseña desde cero  con una metodología divertida y sencilla a aprender a bailar los 6 Ritmos Latinos más conocidos... ",
      "body": "Desde HOY puedes comenzar aprender a bailar de una forma fácil y divertida. Salsa, Merengue, Bachata, Champeta, Reggaeton y Vallenato. Te explico cómo lo vas a lograr en este corto vídeo. Es un super video curso FULL HD, que te enseña desde cero  con una metodología divertida y sencilla a aprender a bailar los 6 Ritmos Latinos más conocidos y bailados en el mundo que cualquier persona puede bailar. Es el entrenamiento número 1 de baile durante la pandemia, campeón de ventas y resultados asombrosamente rápidos. NO TE QUEDES SENTADO MIENTRAS LOS DEMAS DISFRUTAN DE LA FIESTA! Desde HOY puedes comenzar a aprender a bailar de una forma fácil y divertida",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 71,
      "cashback": 2.5,
      "precio_regular": 70,
      "precio": 34.99
    },
    {
      "id": 7,
      "idhotmart": 2446561,
      "ad_id": 0,
      "title": "Danzas Andinas Terapia Energética",
      "slug": "danzas-andinas-terapia-energetica",
      "content": "Bailar nos beneficia a todos, sin importar la edad o las complicaciones de salud que estemos experimentando. A través del ritmo y el movimiento, la energía que recubre nuestro cuerpo se transforma y nos permite sanar enfermedades físicas y psíquicas.... ",
      "body": "En esta formación trabajaremos el movimiento, añadiendo expresión, que es lo que nos permitirá liberar energías bloqueadas, esas emociones que han sido contenidas. Esta terapia de sanación te permite conectarte con seres divinos, la naturaleza y otras personas. Descubrirás cómo elevarte, liberarte de cadenas y máscaras, para encontrar tu verdadero Ser. Con unos sencillos movimientos, fáciles de poner en práctica, podrás equilibrar tus emociones, tus pensamientos, tus sensaciones y también, tu cuerpo físico. Bailando potenciarás tu belleza e inteligencia, tu vida mejorará en todos los aspectos y alcanzarás metas que antes parecían imposibles.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 71,
      "cashback": 2,
      "precio_regular": 54,
      "precio": 27
    },
    {
      "id": 8,
      "idhotmart": 1671528,
      "ad_id": 0,
      "title": "Instructorado de Ritmos",
      "slug": "instructorado-de-ritmos",
      "content": "Estudia con nosotros!! Dicta clases de Ritmos como todo un Profesional! Te recibes con doble titulación! Aval Internacional en 6 Paises mas Certificación Universitaria...",
      "body": "Estudia con nosotros!! Dicta clases de Ritmos como todo un Profesional! Te recibes con doble titulación! Aval Internacional en 6 Paises mas Certificación Universitaria. MUSICA ADAPTADA A LA DANZA (INTERPRETACION MUSICAL-PUESTA ES ESCENA-MUSICA) GUIA DE CLASE.- SISTEMAS DE COREOGRAFIAS HISTORIA DE LOS RITMOS (MERENGUE-CHA-CHA-CHAREGGAETON-DANZA DEL VIENTRE-AXE-BRASILEROSALSA-BACHATA-CUMBIA-ROCK & ROLL- DISCO-ETC. RITMOS: SALSA. CHA –CHA- CHÁ. MERGENGUE. REGGAETON. AXE. BRASILERO. CUMBIA. CUARTETO.ARABE. DISCO. ROCK&ROLL. Y MUCHOS MAS!",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 63,
      "cashback": 10,
      "precio": 106.59
    },
    {
      "id": 9,
      "idhotmart": 2411366,
      "ad_id": 0,
      "title": "Bachata desde Cero",
      "slug": "bachata-desde-cero",
      "content": " Con el Entrenamiento  BACHATA DESDE CERO, baila un ritmo arraigado en la sangre y los beats del corazón de miles de individuos.... ",
      "body": "Hoy, La bachata pertence a los géneros musicales bailables más populares y emblemáticos de República Dominicana. Está poniendo a vibrar al planeta entero. Con el Entrenamiento  BACHATA DESDE CERO, baila un ritmo arraigado en la sangre y los beats del corazón de miles de individuos. Todos los días, más gente elige este programa. Esta es una metodología comprobada para que aprendas a bailar BACHATA en menos de 30 días sin que poseas un conocimiento previo.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 53,
      "cashback": 2,
      "precio": 39.99
    },
    {
      "id": 10,
      "idhotmart": 2178898,
      "ad_id": 0,
      "title": "Bachata",
      "slug": "bachata",
      "content": "Con este Curso Profesional de Bachata bilingüe, te aseguramos que no solo aprenderás a bailarla, sino también disfrutarás e impresionaras en la pista con la serie de movimientos y combinaciones que hemos traído para ti....",
      "body": "Hola Somos Seemore Johnson y Cristina Pujol Instructores profesionales de la escuela Hips On Fire. Con este Curso Profesional de Bachata bilingüe, te aseguramos que no solo aprenderás a bailarla, sino también disfrutarás e impresionaras en la pista con la serie de movimientos y combinaciones que hemos traído para ti. Podrás pasar de no bailar bien a lucirte como un profesional en la pista . Con más de 25 años de experiencia en la enseñanza del baile popular afro latino. Hemos estado impartiendo clases, talleres, demostraciones y shows en 22 países en 4 de los 5 continentes que tiene este planeta. Gozamos de un excelente reconocimiento internacional. Basta con hacer una busqueda en Google para poder comprobar nuestras credenciales. La bachata es uno de los bailes que mejor dominamos, por lo que con toda confianza pueden tomar este curso, sabiendo que los resultados van a ser excelentes.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español | Inglés",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2,
      "precio": 49
    },
    {
      "id": 11,
      "idhotmart": 2157740,
      "ad_id": 0,
      "title": "Curso de Kizomba",
      "slug": "curso-de-kizomba",
      "content": "El curso está diseñado para que los alumnos puedan ir de nivel cero a nivel intermedio-alto...",
      "body": "El curso está diseñado para que los alumnos puedan ir de nivel cero a nivel intermedio-alto. El curso también contiene una serie de vídeos especialmente dirigidos a trabajar el movimiento de las chicas. Con más de 25 años de experiencia en la enseñanza del baile popular afro latino. Hemos estado impartiendo clases, talleres, demostraciones y shows en 22 países en 4 de los 5 continentes que tiene este planeta. Gozamos de un excelente reconocimiento internacional. Basta con hacer una búsqueda en Google para poder comprobar nuestras credenciales. La Kizomba es uno de los bailes que mejor dominamos, por lo que con toda confianza pueden tomar este curso, sabiendo que los resultados van a ser excelentes. Esperamos que sea de tu agrado y lo disfrutes.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español | Inglés",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2,
      "precio": 49
    },
    {
      "id": 12,
      "idhotmart": 915657,
      "ad_id": 0,
      "title": "Danza Árabe en 30 días",
      "slug": "danza-arabe-en-30-dias",
      "content": "Descubre El Maravilloso Mundo De La Danza Árabe en Tan Sólo 30 Días...",
      "body": "Te llevaré de la mano por los movimientos esenciales de esta danza, con la mejor explicación técnica y realización de ejercicios, quemarás cientos de calorías,  te diviértirás y re-descubrirás tu feminidad a través de la danza de medio oriente.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 36,
      "cashback": 1,
      "precio": 24
    },
    {
      "id": 13,
      "idhotmart": 1761213,
      "ad_id": 0,
      "title": "20 lecciones de tango",
      "slug": "20-lecciones-de-tango",
      "content": "El curso ideal para las personas que quieren entrar en el mundo del tango. Desde afuera la danza de tango parece muy compleja, pero en la práctica, la danza de tango es muy simple...",
      "body": "El curso ideal para las personas que quieren entrar en el mundo del tango.Desde afuera la danza de tango parece muy compleja, pero en la práctica, la danza de tango es muy simple. Mis alumnos siempre dijeron antes de empezar a bailar -'es que yo soy de madera, nunca voy a aprender.'- Yo les miro a los ojos y les digo -'Usted ya está aprendiendo'-. Puedo garantizarle que todos mis alumnos han logrado sacarse el miedo a la danza, y hoy en día son felices bailando lo que más les apasiona: el Tango. Es de ese modo que lo invitamos a introducirse en la metodología 'Undertango', conceptos, ideas, reflexiones, ejercicios, prácticas, que lo van a ir guiando para que usted también pueda darse ese especial gusto de bailar un buen y placentero tango y sentirse pleno al hacerlo.",
      "vsl": "https://www.youtube.com/embed/RLMhH_SD56U",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 50,
      "cashback": 1,
      "precio": 14
    },
    {
      "id": 14,
      "idhotmart": 2297537,
      "ad_id": 0,
      "title": "30 Pasos Intermedios de Salsa Caleña",
      "slug": "30-pasos-intermedios-de-salsa-calena",
      "content": "En este curso aprenderás los pasos básicos de la salsa caleña para que los incorpores a tu baile...",
      "body": "En este curso aprenderás los pasos básicos de la salsa caleña para que los incorpores a tu baile. Las clases están estructuradas de manera que puedas practicarlas una por una para que te resulte muy fácil aprender cada uno de los pasos.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 71,
      "cashback": 2,
      "precio": 29
    },
    {
      "id": 15,
      "idhotmart": 2452953,
      "ad_id": 0,
      "title": "Sevillanas desde cero",
      "slug": "sevillanas-desde-cero",
      "content": "Si te sientes abrumada con tantos compromisos y hace falta dedicar tiempo de calidad a ti misma, este curso es para ti...",
      "body": "Si te sientes abrumada con tantos compromisos y hace falta dedicar tiempo de calidad a ti misma, este curso es para ti. Si eres de aquellas que buscas una transformación personal, la danza es una herramienta poderosa para ayudarte a lograr tus metas, ya que posibilita nuevas conexiones neuronales, estimula la producción de dopamina, ayuda en la concentración y, definitivamente, es ¡muy divertido! Objetivo: dar a conocer el baile ‘Sevillanas’, como se bailan las coplas a través de la explicación, paso a paso, del marcaje. Los alumnos recebarán material de apoyo por escrito para facilitar el aprendizaje.",
      "vsl": "https://www.youtube.com/embed/RLMhH_SD56U",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 27,
      "cashback": 3,
      "precio": 89
    },
    {
      "id": 16,
      "idhotmart": 1879217,
      "ad_id": 0,
      "title": "Danza Pilates: Capacitacion intensiva",
      "slug": "danza-pilates-capacitacion-intensiva",
      "content": "DANZAPILATES es una técnica de movimiento que fusiona la Danza, Pilates Mat y Expresión Corporal. Busca la integración de ser, uniendo cuerpo y mente...",
      "body": "DANZAPILATES es una técnica de movimiento que fusiona la Danza, Pilates Mat y Expresión Corporal. Busca la integración de ser, uniendo cuerpo y mente. Esta capacitación es ideal para bailarines, profesores de danza o instructores. También para todo aquel que desee buscar una manera de moverse desde la conciencia corporal y el autoconocimiento.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "danzas y bailes",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 44,
      "cashback": 2.5,
      "precio": 54
    },
    {
      "id": 17,
      "idhotmart": 1638547,
      "ad_id": 0,
      "title": "Máster en guitarra acústica",
      "slug": "master-en-guitarra-acustica",
      "content": "encontrarás todo lo que necesitas, desde técnicas de calentamiento y creación de un plan de estudio efectivo, hasta guías paso a paso para realizar acompañamientos virtuosos, arreglos y composiciones para guitarra...",
      "body": "encontrarás todo lo que necesitas, desde técnicas de calentamiento y creación de un plan de estudio efectivo, hasta guías paso a paso para realizar acompañamientos virtuosos, arreglos y composiciones para guitarra. Entender la guitarra de manera integral te proporcionará una visión amplia de tus oportunidades a medio y largo plazo, permitiéndote interpretar lo que desees y colaborar fácilmente con otros músicos. Desarrollarás la habilidad de escuchar atentamente y encontrar notas y ritmos en tu guitarra con facilidad.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 45,
      "cashback": 4,
      "precio": 97
    },
    {
      "id": 18,
      "idhotmart": 295191,
      "ad_id": 0,
      "title": "Batería Sin Teoría",
      "slug": "bateria-sin-teoria",
      "content": "El único curso online que te lleva de la mano desde: 'no puedo mantener el tiempo'... Hasta... 'puedo sacar canciones, improvisar e incluso puedo entrar a un estudio y grabar como todo un profesional'...",
      "body": "El único curso online que te lleva de la mano desde: 'no puedo mantener el tiempo'... Hasta... 'puedo sacar canciones, improvisar e incluso puedo entrar a un estudio y grabar como todo un profesional'.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 36,
      "cashback": 3,
      "precio": 69
    },
    {
      "id": 19,
      "idhotmart": 1999654,
      "ad_id": 0,
      "title": "Aprende Ritmos Latinos en Piano",
      "slug": "aprende-ritmos-latinos-en-piano",
      "content": "Con éste curso tendrás la probabilidad de llegar muy lejos en la música aplicando todos los ejercicios y lecciones que aquí enseño desde cero a nivel experto...",
      "body": "Si te apasiona tocar el piano y estas en un nivel básico intermedio y deseas aprender mucho más como Ritmos latinos? Éste entrenamiento es para ti, No dejes pasar esta oportunidad de sacarle el máximo provecho a tu Piano aprendiendo ritmos latinos como: SALSA, MERENGUE, BACHATA, SON, CUMBIA, CHACHACHÁ, BOLERO, SONGO, PLENA, REGGAE, RUMBA, BOSSA NOVA, LATIN JAZZ, Entre otros más.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 62,
      "cashback": 3,
      "precio": 49.99
    },
    {
      "id": 20,
      "idhotmart": 1133290,
      "ad_id": 0,
      "title": "Curso de Ukulele para principiantes",
      "slug": "curso-de-ukulele-para-principiantes",
      "content": "En el Curso de Ukulele para principiantes, aprenderás a utilizar tu instrumento para sorprender con tu talento a los demás, de una forma dinámica tranquila y divertida...",
      "body": "En el Curso de Ukulele para principiantes, aprenderás a utilizar tu instrumento para sorprender con tu talento a los demás, de una forma dinámica tranquila y divertida con disciplina y constancia te llevare paso a paso en tu formación musical. Bienvenidos a este lenguaje universal la Música.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 63,
      "cashback": 4,
      "precio": 70
    },
    {
      "id": 21,
      "idhotmart": 1133460,
      "ad_id": 0,
      "title": "Mentoring Guitarra y Canto para principiantes",
      "slug": "mentoring-guitarra-y-canto-para-principiantes",
      "content": "Dentro del curso vas a ver diferentes métodos de aprendizaje para utilizar tu guitarra y canto para sorprender con tu talento a los demás...",
      "body": "Dentro del curso vas a ver diferentes métodos de aprendizaje para utilizar tu guitarra y canto para sorprender con tu talento a los demás, este incluye una temática bien estructurada paso a paso con buen material de estudio para tu formación musical.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 72,
      "cashback": 7,
      "precio": 97
    },
    {
      "id": 22,
      "idhotmart": 920392,
      "ad_id": 0,
      "title": "Aprenda a Cantar",
      "slug": "aprenda-a-cantar",
      "content": "Aprenda a Cantar con Adrian Lozano es un método para aquellos que quieren aprender a cantar con una técnica refinada de manera sencilla, práctica y profesional...",
      "body": "Aprenda a Cantar con Adrian Lozano es un método para aquellos que quieren aprender a cantar con una técnica refinada de manera sencilla, práctica y profesional. Este método fue creado durante 20 años dando clases de canto y dándose cuenta de las principales dificultades de los estudiantes para comprender algunas técnicas de canto. ¡A través de este método, aprenderá de manera práctica a cantar bien! Contienen asignaturas para principiantes, intermedios y avanzados.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 67,
      "cashback": 3,
      "precio": 49.99
    },
    {
      "id": 23,
      "idhotmart": 1681498,
      "ad_id": 0,
      "title": "Canta y Encanta",
      "slug": "canta-y-encanta",
      "content": "Aprende a cantar desde cero. Cumple tu sueño de cantar tus canciones favoritas ahorrando los altos costos de un curso presencial. De una manera fácil, rápida y sin salir de casa...",
      "body": "Aprende a cantar desde cero. Cumple tu sueño de cantar tus canciones favoritas ahorrando los altos costos de un curso presencial. De una manera fácil, rápida y sin salir de casa. A travez de 20 lecciones en video Full HD que podrás ver cuando quieras y las veces que quieras. Donde te enseñaré a adquirir todo el conocimiento, práctica y habilidad que necesitas para poder cantar como todo un Master.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 70,
      "cashback": 2,
      "precio": 24.99
    },
    {
      "id": 24,
      "idhotmart": 1376944,
      "ad_id": 0,
      "title": "Guitarra Master",
      "slug": "guitarra-master",
      "content": "Aprende a tocar la Guitarra desde cero. Cumple tu sueño de tocar tus canciones favoritas ahorrando los altos costos de un curso presencial. De una manera fácil, rápida y sin salir de casa...",
      "body": "Aprende a tocar la Guitarra desde cero. Cumple tu sueño de tocar tus canciones favoritas ahorrando los altos costos de un curso presencial. De una manera fácil, rápida y sin salir de casa. A través de más de 50 lecciones en video Full HD que podrás ver cuando quieras y las veces que quieras. Donde te enseñaré a adquirir todo el conocimiento, práctica y habilidad que necesitas para poder tocar la Guitarra como todo un Máster.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 71,
      "cashback": 3.5,
      "precio": 49.99
    },
    {
      "id": 25,
      "idhotmart": 1569151,
      "ad_id": 0,
      "title": "Aprende a Cantar desde cero",
      "slug": "aprende-a-cantar-desde-cero",
      "content": "El secreto mejor guardado para que ganes confianza y logres cantar como siempre has querido...",
      "body": "La metodología es muy practica y fácil de seguir, el formato es muy infográfico (audio, vídeo e imagen) para que todos los conceptos te queden super claros 'No es el típico curso de youtube', disponible para siempre 24/7, puedes repasar las veces que quieras, TODO a través de un MasterClass con màs de 30 lecciones poderosas para que pierdas el miedo a cantar y logres tener la voz que siempre has querido. Tendrás más de 5 horas y media de información aplicable y obtendrás acceso adicional a los archivos de audio de todos los ejercicios para que practiques donde y cuando quieras.",
      "vsl": "",
      "author": "",
      "evaluacion": "",
      "date": "15-06-2023",
      "categoria": "música",
      "formato": "video curso",
      "productor": "",
      "idioma": "Español",
      "pais": "",
      "suscripcion": "único pago",
      "comission": 71,
      "cashback": 1,
      "precio": 21
    }
  ]
}
